version: '3.8'

services:
  openmanus:
    build: .
    container_name: openmanus
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
